comment:
  header: Hi, there.
  footer: "\
    ---\n\n\
    > This is an automated comment created by the [peaceiris/actions-label-commenter]. \
    Responding to the bot or mentioning it won't have any effect.\n\n\
    [peaceiris/actions-label-commenter]: https://github.com/peaceiris/actions-label-commenter"

labels:
  - name: invalid
    labeled:
      issue:
        body: &invalid_labeled_body Please follow the {{ eventName }} templates.
        action: close
      pr:
        body: *invalid_labeled_body
        action: close
        draft: true
    unlabeled:
      issue: &invalid_unlabeled_issue
        body: &invalid_unlabeled_body |
          Thank you for following the {{ eventName }} template. The repository owner will reply.
        action: open
      pr: *invalid_unlabeled_issue
  - name: forum
    labeled:
      issue:
        body: |
          Please ask questions about GitHub Actions at the following forum.
          https://github.community/c/github-actions
        action: close
  - name: wontfix
    labeled:
      issue:
        body: This {{ eventName }} will not be worked on but we appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This {{ eventName }} has become active again.
        action: open
  - name: duplicate
    labeled:
      issue:
        body: This {{ eventName }} already exists.
        action: close
  - name: good first issue
    labeled:
      issue:
        body: This {{ eventName }} is easy for contributing. Everyone can work on this.
  - name: proposal
    labeled:
      issue:
        body: Thank you @{{ author }} for suggesting this.
  - name: locked (spam)
    labeled:
      issue: &locked_spam_labeled_issue
        body: &locked_spam_body |
          This {{ eventName }} \#{{ number }} has been **LOCKED** with the label {{ labelName }}!

          Please do not spam messages on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr: *locked_spam_labeled_issue
      discussion:
        body: *locked_spam_body
        locking: lock
        lock_reason: spam
        answer: true
  - name: locked (heated)
    labeled:
      issue: &locked_heated_labeled
        body: |
          This {{ eventName }} has been **LOCKED** because of heated conversation!

          We appreciate exciting conversations, as long as they won't become too aggressive and/or emotional.
        locking: lock
        lock_reason: too heated
      pr: *locked_heated_labeled
      discussion: *locked_heated_labeled
    unlabeled:
      issue: &locked_heated_unlabeled
        body: |
          This {{ eventName }} has been unlocked now.
        locking: unlock
      pr: *locked_heated_unlabeled
      discussion: *locked_heated_unlabeled
  - name: locked (off-topic)
    labeled:
      issue:
        body: |
          This {{ eventName }} has been **LOCKED** because of off-topic conversations!

          Please use our other means of communication for casual chats.
        action: close
        locking: lock
        lock_reason: off-topic
  - name: locked (resolved)
    labeled:
      issue:
        body: &locked_resolved_labeled_body |
          This {{ eventName }} has been **LOCKED** because of it being resolved!

          If you still encounter this or it has changed, open a new {{ eventName }} instead of responding to solved ones.
        action: close
        locking: lock
        lock_reason: resolved
      discussion:
        body: *locked_resolved_labeled_body
        locking: lock
        lock_reason: resolved
  - name: documentation
    labeled:
      pr:
        body: "\
          [The documentation label] was added. \
          Thank you for suggesting documentation improvement.\n\
          When you add a new section, do not forget to update the Table of Contents.\n\n\
          ```sh\n\
          npx doctoc --github README.md\n\
          ```\n\n\
          [The documentation label]: https://github.com/peaceiris/actions-label-commenter/issues?q=label%3Adocumentation\n
          "
