name: 'Label Commenter'
description: 'Label triggered GitHub Action for posting a template comment, open/close/lock/unlock issue or pull-request automatically.'
author: 'peaceiris'
inputs:
  github_token:
    description: 'Auth token used to manage issues or pull requests'
    default: ${{ github.token }}
    required: false
  config_file:
    description: 'Path to action setting file'
    default: '.github/label-commenter-config.yml'
    required: false
runs:
  using: 'node16'
  main: 'dist_release/index.js'
branding:
  icon: 'tag'
  color: 'orange'
