name: 'Label Commenter'
description: 'Label triggered GitHub Actions for posting a template message, automatically close or reopen issues or pull requests.'
author: 'peaceiris'
inputs:
  github_token:
    description: 'Auth token used to manage issues or pull requests'
    default: ${{ github.token }}
    required: false
  config_file:
    description: 'Path to action setting file'
    default: '.github/label-commenter-config.yml'
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'tag'
  color: 'orange'
