name: Lint Workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
  pull_request:
    paths:
      - '.github/workflows/*'

jobs:
  actionlint:
    uses: peaceiris/workflows/.github/workflows/actionlint.yml@v0.20.0
