name: Lint Workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
  pull_request:
    paths:
      - '.github/workflows/*'

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - uses: docker://rhysd/actionlint:latest
        with:
          args: -color
