name: 'Dev Image CI'

on:
  workflow_dispatch:
  schedule:
    - cron: '11 11 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'
      - 'docker-compose.yml'
  pull_request:
    paths:
      - '.github/workflows/dev-image.yml'
      - '.dockerignore'
      - '.nvmrc'
      - 'Dockerfile'
      - 'Makefile'
      - 'docker-compose.yml'

permissions:
  contents: read
  packages: write

jobs:
  dev-image-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 4
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Login to Packages
        run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login 'docker.pkg.github.com' -u 'peaceiris' --password-stdin
      - run: docker-compose pull --quiet
        if: github.event_name == 'pull_request'
      - run: make build
      - run: docker images
      - run: make ci
      - run: make all
      - run: docker-compose push
        if: github.ref == 'refs/heads/main'
